env:
 - GHCVER=7.4.2
 - GHCVER=7.6.3
 - GHCVER=7.8.4
 - GHCVER=7.10.1
 - GHCVER=head

matrix:
  allow_failures:
   - env: GHCVER=head

script:
 - cabal configure -fdev --enable-tests && cabal build && cabal test tests
